runtime: python27
api_version: 1
threadsafe: true
env_variables:
  FLASK_SECRET_KEY: tanarky
#  BUCKET_NAME: welcome-to-tokyo.appspot.com

handlers:
- url: /s
  static_dir: static
- url: /.*
  script: main.app
